# Generated by Django 6.0.5 on 2026-05-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
